name: README build

on:
  push:
    branch:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v4
      - name: Setup Nodejs 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-{{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Report deployment status to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          STATUS="${{ job.status }}"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "🚀 README build workflow finished with status: **'$STATUS'** on branch `${{ github.ref }}`. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>"}' \
            "$DISCORD_WEBHOOK"
